/**
Server.JS
Version: 1.0.0
Date: 4/26/2017

A server file written for express that serves a basic webpage flow to demonstrate connection to a Citi API.

Uses Async for synchronous API calls, Axios for HTTP requests, and body-parser for formatting data.
*/

//Library imports
const express = require('express');
const path = require('path');
const https = require('https');
const fs = require('fs');
const async = require('async');
const bodyParser = require('body-parser');
const axios = require('axios');
const querystring = require('querystring');
const config = require('./config.json');

//initialize express
var app = express();

// Parsers for POST data
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));

//options for https server - use certificate generated by openssl
var options = {
  key: fs.readFileSync('key.pem'),
  cert: fs.readFileSync('cert.pem'),
  passphrase: config.CERTIFICATE_PASSWORD
};

var routes = require('./routes')
app.use('/', routes);

//port assignment for local server
const port = process.env.PORT || '3000';
app.set('port', port);

//create https server with options for https
const server = https.createServer(options, app);

//display console message for where server is listening
server.listen(port, () => console.log(`API running on localhost:${port}`));




function filterDataByMonth(monthInput, yearInput){
	var i = 0;
	var filteredData = {};
	Object.keys(transactionData).forEach(function(key) {
		Object.keys(transactionData[key]).forEach(function(subkey){
			var dateObject = new Date(transactionData[key][subkey]['transactionDate']);
			var dataMonth = dateObject.getMonth()+1;
			var dataYear = dateObject.getFullYear();
			transactionData[key][subkey]['accountType'] = key;
			if(dataMonth===monthInput && yearInput===dataYear){
				filteredData[i] = transactionData[key][subkey] ;
				i++;
			}
		})
	});
	console.log(filteredData);
	return filteredData;
}

